### ISSUE TITLE
 The connection string is missing the property: DeviceId

### ISSUE THREAD

**Issue by salmanfarisvp** [Azure-Samples/iot-hub-node-raspberrypi-client-app#10]
i completed all  steps and am using Rpi3 .
when run the code  it throw an error 
```
/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/az-iot-bi/node_modules/applicationinsights/AutoCollection/Exceptions.js:27
                        throw error;
                        ^
ArgumentError: The connection string is missing the property: DeviceId
    at /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device/node_modules/azure-iot-common/lib/connection_string.js:21:31
    at Array.forEach (native)
    at Function.parse (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device/node_modules/azure-iot-common/lib/connection_string.js:20:18)
    at Object.parse (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/azure-iot-device/lib/connection_string.js:13:33)
    at initClient (/home/pi/iot-hub-node-raspberrypi-client-app/index.js:83:43)
    at /home/pi/iot-hub-node-raspberrypi-client-app/index.js:135:12
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/index.js:158:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

```
i added the Device id in the `config .json` file , but it still showing the error.

**Comment by SLdragon** [comment]
Maybe you are using a wrong device connection string,

1. Device connection string muse be  in format HostName=xxx;DeviceId=xxx;SharedAccessKey=xxx
2. The device connection string should be quoted in the command
3. You should run the client app using the command like this:
```bash
sudo node index.js '<your Azure IoT hub device connection string>'
```

**Comment by salmanfarisvp** [comment]
Thank you @SLdragon ,
