### ISSUE TITLE
Error: Cannot find module '../build/Release/wiringPi'

### ISSUE THREAD

**Issue by slik1011** [Azure-Samples/iot-hub-node-raspberrypi-client-app#18]
Hello,

I have completed the installation as required and when I try to connect to Azure IoT Hub, I get this error:

```
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '../build/Release/wiringPi'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/wiring-pi/lib/exports.js:1:80)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

During the installation, I also got this message, which I think my be related to the problem:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/i2c-bus/.node-gyp/9.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/i2c-bus/.node-gyp"
```
Does anyone know why this happens?
Thank you for any suggestions.

**Comment by ajiteshg** [comment]
Yes, go back and fix installation.
for example if you are using mac, then
$sudo npm install
If it asks to fix anything, then
$npm audit fix

This should resolve your issues.

**Comment by hermanarenas** [comment]
Same problem here, could you be more specific about the fix, the installation loops endesly on
 gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/i2c-bus/.node-gyp/9.11.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/i2c-bus/.node-gyp"

**Comment by datasharkNL** [comment]
I've tried this solution from @masonpawsey and that works for me:
https://github.com/Azure-Samples/iot-hub-node-raspberrypi-client-app/issues/33#issuecomment-576485182
