### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by ankurp16** [Azure-Samples/iot-hub-node-raspberrypi-client-app#23]
Fresh rasbian install.

![mvimg_20190208_114727](https://user-images.githubusercontent.com/47457981/52495102-b949eb80-2b9d-11e9-9f55-07b2dee6ac4d.jpg)

**Comment by Alberto-Vega-MSFT** [comment]
[inesk-vt](/inesk-vt) Moving this issue here from [Issues succesfully installing node.js per tutorial steps](https://github.com/MicrosoftDocs/azure-docs/issues/24298) 

I set up my OS a few weeks ago following steps from another Azure IoT tutorial that pointed to : https://www.raspberrypi.org/downloads/raspbian/. Below is the OS version on my system, is it supported for this tutorial?

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

I have tried completing the tutorial, but now hitting issues running the sample app, complains about not finding bindings.

sudo node index.js 'HostName=InesKAppSandbox.azure-devices.net;DeviceId=InesKDeskPi;SharedAccessKey=MnzQEG7yxinQVLrWYj1Ms8ogIzryCbgox9McIkkb/yI='
/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:91
throw err
^

Error: Could not locate the bindings file. Tried:
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/nodeWiringPi.node
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Debug/nodeWiringPi.node
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Debug/nodeWiringPi.node
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Debug/nodeWiringPi.node
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Release/nodeWiringPi.node
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Release/nodeWiringPi.node
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/default/nodeWiringPi.node
→ /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/compiled/11.9.0/linux/arm/nodeWiringPi.node
at bindings (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:88:9)
at Object. (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/index.js:1:99)
at Module._compile (internal/modules/cjs/loader.js:734:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
at Module.load (internal/modules/cjs/loader.js:626:32)
at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
at Function.Module._load (internal/modules/cjs/loader.js:558:3)
at Module.require (internal/modules/cjs/loader.js:663:17)
at require (internal/modules/cjs/helpers.js:20:18)
at Object. (/home/pi/iot-hub-node-raspberrypi-client-app/index.js:10:13)

Thanks.

**Comment by weisssean** [comment]
Any information on this? Was this ever resolved?

**Comment by mohsinonxrm** [comment]
having the same issue on raspberry pi 4B, with latest node etc.

**Comment by jopapeador18** [comment]
Im having the same issue. Any one solved?

**Comment by TheCaarlos7** [comment]
@jojapeador18 I'm having the same issue too.
I am working on raspberry model 3+ with all the updates and i get the same error. anyone have a solution, we are trying to connect the bme280 to azure with the raspberry but any path seems to work fine.
If anyone could help me, it would be great.

**Comment by jopapeador18** [comment]
This is the error im getting:

pi@raspberrypi:~/iot-hub-node-raspberrypi-client-app $ sudo node index.js 'HostName=rasberryipi.azure-devices.net;DeviceId=rpi4jose;SharedAccessKey=XXXXX'
/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/default/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/compiled/11.15.0/linux/arm/nodeWiringPi.node
    at bindings (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:816:30)

Im currently under nodej version v.11.15 and i have tried the following commands:

rm -rf node_modules
npm install

After that you can try again:
sudo node index.js '<YOUR AZURE IOT HUB DEVICE CONNECTION STRING>'

BR.

**Comment by TheCaarlos7** [comment]
@jopapeador18 i've tried these commands but i'm getting the same error.
i dont know what to do...

**Comment by weisssean** [comment]
I got it to work like this:


package.json:
        "az-iot-bi": "^0.1.20",
        "azure-iot-device": "^1.12.0",
        "azure-iot-device-amqp": "^1.11.0",
        "azure-iot-device-mqtt": "^1.11.0",
        "bme280-sensor": "^0.1.6",
        "onoff": "^5.0.0"

Dockerfile:
FROM resin/raspberrypi3-node:8

WORKDIR /app

# Install dependencies
RUN echo "deb http://deb.debian.org/debian jessie main" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
    apt-utils \
    build-essential \
    curl \
    python-dev \
    python-pip \
    python-setuptools \
    swig \
    zlib1g-dev

COPY . .

RUN pip install --upgrade pip
RUN pip install ptvsd==4.1.3
RUN pip install -r requirements.txt \
    RPi.GPIO

RUN npm install

EXPOSE 9229

CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]

Add a .dockerignore file with:
`node_modules`

*Note
_I haven't cleaned up dependencies yet so a lot of them might be unnecessary._

Hope this helps...

**Comment by TheCaarlos7** [comment]
@weisssean when i try this command: RUN echo "deb http://deb.debian.org/debian jessie main" >> /etc/apt/sources.list. I am getting this message --> -bash: /etc/apt/sources.list: Permission denied
could you help me?

**Comment by julie-wins** [comment]
FWIW Jan 2020 I am running into the same issue when I try to connect using my connection string - can't find bindings. Have not tried yet @weisssean steps.

**Comment by codepoet80** [comment]
I'm having the same issue. I noticed significant error output when running npm install.
This is on a clean install of latest Buster, with the version of Node recommended in the docs: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-raspberry-pi-kit-node-get-started#register-a-new-device-in-the-iot-hub

npm install error output attached.
Runtime error is the same as reported above.

[npm-install-error.txt](https://github.com/Azure-Samples/iot-hub-node-raspberrypi-client-app/files/4129951/npm-install-error.txt)

**Comment by datasharkNL** [comment]
I've tried this solution from an other issue, and that works for me like a charm:
https://github.com/Azure-Samples/iot-hub-node-raspberrypi-client-app/issues/33#issuecomment-576485182

**Comment by atosrdbms** [comment]
Hi,

Did anyone find a solution for the Binding-warning?

/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/default/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/compiled/10.19.0/linux/arm/nodeWiringPi.node
    at bindings (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)


Regards,
Mark

**Comment by codepoet80** [comment]
> Did anyone find a solution for the Binding-warning?

I couldn't find a solution, and none of the suggestions worked. I did find a work around: use Azure IOTCentral as the point of ingress, and from there you can send the data to Stream Analytics job and send the output anywhere you want (SQL Azure, Table, Blob, PowerBI, Function, etc...)

The tutorials and templates for IOT Central are current, and work well:
https://docs.microsoft.com/en-us/azure/iot-central/core/howto-connect-raspberry-pi-python#raspberry-pi-device-template-details

**Comment by julie-wins** [comment]
I found this helped. Basically, turn off the blinking light calls:
https://github.com/Azure-Samples/iot-hub-node-raspberrypi-client-app/issues/33#issuecomment-576485182

Making those changes, I got the Pi sending simulated data to my consumer group, and I was able to present that with a web servlet on my PC.
