### ISSUE TITLE
Unable to install npm

### ISSUE THREAD

**Issue by Birdeyman** [Azure-Samples/iot-hub-node-raspberrypi-client-app#28]
Have worked through the tutorial on 2 different raspberry pi cards now and get the same issue on both. At the point of running npm install, results in the following:

/home/pi/.node-gyp/11.15.0/include/node/v8.h:9710:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [nodeWiringPi.target.mk:116: Release/obj.target/nodeWiringPi/src/wiringPi.o] Error 1
make: Leaving directory '/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN iot-hub-node-raspberrypi-client-app@1.0.0 No repository field.

added 259 packages from 342 contributors and audited 1088 packages in 68.755s
found 0 vulnerabilities

I saw a similar issue listed here where installing node.js 11 rather than 10 resolved the issue, but this did not work in my instance

**Comment by lawlxy** [comment]
I have the same error.

**Comment by KancerKris** [comment]
Same error here too, any fix?

**Comment by 3AGSystems** [comment]
I'm having same issue. I have installed newer verson node.js (v12.14.1) as suggested here but still getting same error when running the npm install in project directory. I got raspberry pi 2. Below is error I'm getting :






make: Leaving directory '/home/pi/Downloads/iot-hub-node-raspberrypi-client-app/node_modules/iring-pi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lid.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gy"configure" "build"
gyp ERR! cwd /home/pi/Downloads/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN iot-hub-node-raspberrypi-client-app@1.0.0 No repository field.

added 256 packages from 349 contributors and audited 1321 packages in 151.96s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by syntetic81** [comment]
same error for me
