### ISSUE TITLE
Could not locate nodeWiringPi.node

### ISSUE THREAD

**Issue by MFConsult** [Azure-Samples/iot-hub-node-raspberrypi-client-app#33]
I have the following failure 

pi@raspberrypi:~ $ cd iot-hub-node-raspberrypi-client-app
pi@raspberrypi:~/iot-hub-node-raspberrypi-client-app $ sudo node index.js '.....'
**/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:91
  throw err
  ^**

Error: Could not locate the bindings file. Tried:
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/default/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/compiled/11.15.0/linux/arm/nodeWiringPi.node
    at bindings (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/index.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:816:30)

i use the newest code with an raspberry pi 4....

I'm super grateful for help!

**Comment by masonpawsey** [comment]
I had the same error, but I was okay just using the simulated data. YMMV.

I pulled out all of the references to the wiring library ([which has been deprecated ](http://wiringpi.com/wiringpi-deprecated/)), removed the `BlinkLED()` function, and ran it *without* sudo. That worked for me

**Comment by KancerKris** [comment]
@masonpawsey  can you give a little more info on this fix, specifically the references to the wiring lib? I'm having the same problem

**Comment by masonpawsey** [comment]
Sure, sorry for the haste of the previous comment. Again, I'm not wired to anything physical, I'm only publishing simulated data. With that in mind:

[Here's what my `index.js` looks like](https://gist.github.com/masonpawsey/33227f03ddc955aa1df5cff0bd9d6d43). You'll notice that I removed the wpi library and any calls to the `blinkLED()` function. The original program intends for an LED to blink when a message is sent or received by the Raspberry Pi. Since I didn't want to wire anything up, I removed this code from my `index.js` file. This solved my build errors, as mine was failing on the `node-wiring-pi` step (again, YMMV).

The final piece of the puzzle is to run *without* `sudo`, like this: 
```
$ node index.js "HostName=XXX;DeviceId=XXX;SharedAccessKey=XXX"
```
You should then see something that looks like this
```
[Device] Using MQTT transport protocol
[Device] Sending message: {"messageId":1,"deviceId":"Raspberry Pi Node","temperature":29.63832366181949,"humidity":71.62597635438006}
[Device] Message sent to Azure IoT Hub
```


Just in case you need, here's my `config.json` as well:

```
{
  "simulatedData": true,
  "interval": 2000,
  "deviceId": "Raspberry Pi Node",
  "LEDPin": 5,
  "messageMax": 256,
  "credentialPath": "~/.iot-hub",
  "temperatureAlert": 30,
  "transport": "mqtt",
  "iotEdgeRootCertFilePath": null,
  "i2cOption": {
    "pin": 9,
    "i2cBusNo": 1,
    "i2cAddress": 119
  }
}
```

Let me know if you have any questions!

**Comment by datasharkNL** [comment]
@masonpawsey you're great! This works like a charm

**Comment by syntetic81** [comment]
@Alberto-Vega this problem still exist could you please help

**Comment by syntetic81** [comment]
@masonpawsey i try your solution but now i get another error:
[Device] Using MQTT transport protocol
{ [Error: ENOENT: no such file or directory, open '/dev/i2c-1'] errno: -2, code: 'ENOENT', syscall: 'open', path: '/dev/i2c-1' }

**Comment by julie-wins** [comment]
I want to +1 @masonpawsey  - that tip worked well, and I've had this running both simulated and actual data.
